version: "3.9"
services:
  app:
    image: my_app:latest
    extra_hosts:
    - "host.docker.internal:host-gateway"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/key.key:/etc/ssl/key.key
      - /etc/ssl/cert.crt:/etc/ssl/cert.crt
    ports:
      - "443:443"
      - "80:80"
